### ISSUE TITLE
Push하려는데 장치에 남은 공간이 없다고 뜹니다.

### ISSUE THREAD

**Issue by minho-park** [naver/yobi#1003]
새로운 브랜치를 만들어서 Push하려고 하는데 장치에 남은 공간이 없다고 합니다.
안쓰는 브랜치 몇 개를 지웠는데도 똑같네요.
Mac OS X 10.10.5
클라이언트로 SourceTree 프로그램을 사용하고 있습니다.

error: unpack failed: error 장치에 남은 공간이 없음

혹시 이런 문제 겪어보신분 계신가요?

**Comment by doortts** [comment]
혹시 말 그대로 디스크가 부족한건 아니신거죠?

ps. 브랜치 지워도 디스크가 늘어나진 않을거에요. 원래.

**Comment by minho-park** [comment]
해결됐습니다. 요비 서버에 문제가 있었나 봅니다.
답변 감사합니다.

**Comment by doortts** [comment]
@minho-park 네. 다행이네요.
그런데 혹시 어떤 문제였고 어떤식으로 해결이 되었는지 공유해 주실수 있을까요?

**Comment by minho-park** [comment]
처음엔 디스크 용량이 없어서 발생했던 문제라 그걸 해결하셨더니 또 다른 문제가 발생했다고 합니다.
'play project의 파일에 문제가 있었다'라고 하시는데 제가 관리자가 아니라 정확한 이유는 모르겠습니다.
