### ISSUE TITLE
http://yobi.d2fest.kr/  서버다운??

### ISSUE THREAD

**Issue by lotiony** [naver/yobi#1004]
yobi를 호스팅하는 서비스가 http://yobi.d2fest.kr/ 맞지요?
어제 가입하고 몇몇 플젝을 올려서 테스트삼아 썼는데
오늘은 접속불가네요?
Service Temporarily Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

데모사이트도 아니고 이거 github 대체해서 쓸수 있는거 아닌가 했는데  
결국 서버하나 따로 파서 yobi를 설치해서 쓰는게 제일 나은건가요?

d2fest가 원래 서버다운이 종종 일어나는건지... 이틀째만에 접속불가해서 못쓰게 되니 영 찜찜하네요

**Comment by npcode** [comment]
알려주셔서 감사합니다.

yobi 호스팅 서버는 아니고 과거 d2fest 대회때 사용한 인스턴스인데요. 일단 살렸습니다.

**Comment by lotiony** [comment]
그렇군요~~ 감사합니다.
repo.yobi.io 하고  yobi.d2fest.kr 하고  동일한 서비스 되는게 맞지요?
그럼 이게 영속성이 보장되지 않는 서비스이겠네요
데모랑은 달리  운영되는 것 같아서  따로 yobi 서버 안만들고 이용할수 있으려나 했는데 ㅎㅎ

여기 만든 프로젝트등을 향후에  따로 구축한 yobi서버로 이전 가능한가요?

**Comment by benelog** [comment]
D2fest를 위한 소스 저장소는 Yobi에서 Gihub로 이관되었습니다.

https://github.com/D2-FEST-2014
