### ISSUE TITLE
http://repo.yobi.io/ 죽은거 같은데요 . 

### ISSUE THREAD

**Issue by inchuli** [naver/yobi#1007]
http://repo.yobi.io/ 죽은거 같은데요

**Comment by npcode** [comment]
살려놓았습니다. 자동 재시작 스크립트에 오류가 있었나보네요. 고쳤습니다.

**Comment by pms790508** [comment]
503 error가 여전히 발생합니다.

**Comment by npcode** [comment]
다른 오류가 있었군요... 다시 고치고 재시작했습니다.

**Comment by benelog** [comment]
repo.yobi.io 는 더이상 운영하지 않습니다.
