### ISSUE TITLE
Yobi 프로젝트 종료 시 현재의 GitHub는 남아 있는 건가요?

### ISSUE THREAD

**Issue by helloppfm** [naver/yobi#1016]
Yobi를 잘 사용하고 있는 사용자인데 이렇게 프로젝트가 종료되어서 무지 아쉽습니다.

지원이 종료된다는 말이 여기 GitHub의 글도 삭제 된다는 의미는 아니죠?

기술적 지원이나 업데이트는 Yona가 대신하더라도 여기에 있는 글들은 남겨두었으면 합니다.

**Comment by doortts** [comment]
네 프로젝트 자체를 없애 버리거나 폐쇄하지는 않을 예정입니다.
