### ISSUE TITLE
Yobi 프로젝트 종료시 기존의 프로젝트들을 이관할 수 있을까요?

### ISSUE THREAD

**Issue by smc0210** [naver/yobi#1017]
안녕하세요.
요비가 29일까지인걸로 들었습니다.
제가 직접 메일을 받진 않았지만 다른 커뮤니티 사용자가 받은 메일을 통해 확인한 부분이라 정확하진 않은데 이 부분에 대한 공지를 볼 수 있는곳이 있을까요?

또한 yona라는 이름의 개인용으로 전환된다고도 들은 것 같은데
이경우 기존의 요비의 프로젝트들을 이관할 수 있을까요?

**Comment by smc0210** [comment]
자문 자답입니다.
아래 링크에서 확인할 수 있었네요
[https://github.com/yona-projects/yona](https://github.com/yona-projects/yona)

**Comment by benelog** [comment]
네, 아마 아직까지는 같은 DB스키마를 쓰므로 데이터를 이전에는 문제가 없을것으로 예상합니다.
