### ISSUE TITLE
비밀번호가 틀리다고 나오는데.. 리셋을 할려니.. 가입한 id가 뭔지 모르겠습니다.

### ISSUE THREAD

**Issue by koolguyjeff** [naver/yobi#1025]
이메일은 : jeff.lee@navercorp.com

입니다.

가입한 id가 뭔지 모르겠습니다.

혹시 리셋 할 수 있는 방법이 있을까요?

**Comment by doortts** [comment]
@koolguyjeff 사이트 어드민에게 문의해보셔야 할 것 같습니다. 그리고 패스워드를 잊었다고 리셋도 같이 해 달라고 요청해주셔야 합니다. 사이트 어드민은 이름이나 이메일로 검색해서 강제로 패스워드를 리셋할 수 있습니다.

그리고 yobi는 더이상 유지보수 되거나 지원되지 않습니다. 
https://github.com/naver/yobi#deprecated

추가적인 지원이나 질문은 Fork 프로젝트인 yona - https://github.com/yona-projects/yona 쪽을 이용해주세요. : )

**Comment by benelog** [comment]
@koolguyjeff 
혹시 yobi 네이버 인스턴스에 대한 것이라면 사내 yobi의 이슈 게시판으로 요청을 해주셨으면 합니다.
