### ISSUE TITLE
페이지를 찾을 수 없습니다

### ISSUE THREAD

**Issue by kimothink** [naver/yobi#1026]
제가 소스트리로 잘못을 했는지 push까지 하니 페이지를 찾을 수 없습니다라고 뜨네요. 이거 제가 잘못한것같은데 어떻게 하면 좋을까요? 마스터가 아닌데 제가 마스터로 깃에서 푸쉬를 했는데 어떻게 하면 좋을까요?

**Comment by doortts** [comment]
프로젝트 설정에 보시면 기본 브랜치를 지정하는 부분이 있습니다. 그부분에서 설정해주세요.

![image](https://cloud.githubusercontent.com/assets/520523/23734593/562f78e2-04c3-11e7-8cc9-7a0b0a8e1cc5.png)

**Comment by doortts** [comment]
@Gojhon 그리고 이곳 yobi는이 프로젝트는 더 이상 유지보수 되거나 지원이 제공되지 않습니다.  죄송하지만 이 이슈는 닫도록 하겠습니다.
