### ISSUE TITLE
프로젝트를 fork했지만 fork가 제대로 작동하지 않는 문제.

### ISSUE THREAD

**Issue by E-nuri** [naver/yobi#1027]
![2017-06-16 10 25 16](https://user-images.githubusercontent.com/20082776/27208047-49ed111c-527e-11e7-808e-32121f6e5ebb.png)

프로젝트를 fork해서 fork된 프로젝트로 들어갔지만 위와 같은 이미지를 보여주며 아무 기능도 사용할 수 없습니다.

프로젝트를 삭제하려고해도 해당 프로젝트 화면이 보여야 할 수 있으므로 해결책이 없는 상황입니다.

**Comment by doortts** [comment]
@E-nuri 
Yobi는 현재 deprecated 되었습니다.
https://github.com/naver/yobi#deprecated

![image](https://user-images.githubusercontent.com/520523/28950691-1452c2f0-7901-11e7-95b1-52d62e2182a1.png)
