### ISSUE TITLE
프로젝트 순서를 변경할 수 있을까요?

### ISSUE THREAD

**Issue by slkikim** [naver/yobi#1028]
안녕하세요.

자주 접속하는 프로젝트가 뒷쪽에 정렬되어 있어
매번 페이지 이동을 해야하는 번거로움이 있습니다.

프로젝트 순서를 변경할 수 있을까요?

감사합니다.

**Comment by doortts** [comment]
![image](https://user-images.githubusercontent.com/520523/28950723-4e9c5372-7901-11e7-9fea-b69a558eeb2e.png)
https://github.com/naver/yobi#deprecated

Yobi fork version인 [Yona](https://github.com/yona-projects/yona)가 개인 프로젝트로 이어서 운영되고 있으니 참고 부탁드립니다.
