### ISSUE TITLE
좀 더 쉬운 배포판 만들기

### ISSUE THREAD

**Issue by keesun** [naver/yobi#794]
주노스펄스로 VPN 접속할라 그랬는데 인증 문자가 안와서 사내망에 접근할 수가 없군요.

예전에도 한번 언급 되었었지만 stage 태스크 사용해서 배포하는 방법이 있습니다.
https://www.playframework.com/documentation/2.0/Production

여기 보면 지금 배포하는 방법말고 stage 태스크를 사용해서 배포버전을 만드는 방법이 있는데요.
실제로 해보니까 잘 동작할 뿐더러, play에 대한 의존성을 jar로 가지고 있어서 유저들이 play를 설치하지 않아도 됩니다.

그러면 유저가 play를 설치해야 하는 수고로움도 덜 수 있을테고 혹시나 설치한 playt 버전이 달라서 문제를 발생할 여지도 예방할 수 있을 듯 합니다.

yobi를 압축해서 내려받게 하고 `target/start`를 실행하게 한다면 유저가 git을 설치해야 하는 부담도 줄일 수 있을 듯 하네요.

**Comment by npcode** [comment]
http://yobi.io/yobi.zip으로 배포하게 되었습니다.
