### ISSUE TITLE
크롬에서는 한글.. 다른 브라우저에서 영어로만뜸..

### ISSUE THREAD

**Issue by bjrambo** [naver/yobi#800]
크롬에서는 한글로 잘 나타나고 있는데,
다른 브라우저에서 lang설정이 영어로만 뜨는 문제점이 있습니다.
기본적으로 언어를 선택하여 사용할 수 있었으면 좋겠습니다 :)

**Comment by snailjh** [comment]
@qw5414  
application.conf 설정파일에서
application.langs="ko, kr, en" 이렇게 고치면 ie에서 동작하더군요 참고 하세요~
