### ISSUE TITLE
시스템 최소 요구사항 질문드립니다

### ISSUE THREAD

**Issue by yongbeam** [naver/yobi#807]
가상호스트로 yobi를 설치중인데요 
아래 컴파일에서 더이상 진해되지 않네요( 7시간을 기다려봤는데도 안되네요 )

가상호스트로 RAM을 512MB를 할당해 주었습니다.
OS는 Ubuntu 12.04 (64bit) 이구요

[info] Compiling 186 Scala sources and 200 Java sources to /home/top6616/play-2.1.0/yobi/target/scala-2.10/classes...
여기서 멈춰있네요

CPU 2core / 512MB RAM 으로는 무리일까요?

현재 평상시 메모리 현황입니다( 단위 - MB )
             total   /    used   /    free  /   shared  /  buffers   /   cached
Mem:           491    /    121   /     369    /      0    /      7     /    41
-/+ buffers/cache:         72    /    418
Swap:          507     /   108    /    399

**Comment by ajkj** [comment]
Swap을 사용하시면 됩니다.
사용하다가 너무 느리다고 생각하시면 램업글이 필요하겠지요...
https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

**Comment by npcode** [comment]
메모리 사용량을 docs/system-requirements.md 문서에 적어야하겠네요.

**Comment by ajkj** [comment]
Q

2015년 5월 15일 금요일, Yi EungJun<notifications@github.com>님이 작성한 메시지:
