### ISSUE TITLE
"ObjectiveC 의 카테고리 파일" 찾을 수 없습니다.

### ISSUE THREAD

**Issue by skyfe79** [naver/yobi#813]
ObjectiveC 에서 카테고리의 파일명은 NSString+md5.m 처럼 관례상 + 기호를 사용하고 있습니다.
Yobi에서 '+' 기호가 들어간 파일을 읽으려면 "페이지를 찾을 수 없습니다"라는 오류가 발생합니다. 

Mac, Yosemite, Java 7 에서 사용하고 있습니다.

**Comment by npcode** [comment]
5016350de928be1f44b01d0be31b80c4c123db29 에서 Play 2.3.6으로 올렸습니다.

**Comment by npcode** [comment]
Play 버전을 올리기만 했는데 해결된 것 같네요. v0.8에 반영될 것입니다.
