### ISSUE TITLE
설치시 네트워크를 사용하지 못할때

### ISSUE THREAD

**Issue by company1234** [naver/yobi#821]
설치 안내파일을 보면

실행하면 필요한 파일들을 web에서 내려받습니다. 첫 실행시 네트워크 상황에 따라 10여분 가까이 소요될 수 있습니다.

이러한 항목이있는데요

../play 로 실행해보니

ivy.xml을 타임아웃 에러나서 못받아오는데,,,  

네트워크가안되면 설치어떻게 해야할까요?

**Comment by npcode** [comment]
http://yobi.io/yobi.zip 으로 배포하게 되었습니다.
