### ISSUE TITLE
그룹 생성시 공개 권한 설정 항목이 수정할때는 없는게 정상인가요?

### ISSUE THREAD

**Issue by namineya** [naver/yobi#825]
그룹 생성시 공개 권한 설정 항목이 있었는데 막상 생성하고 나서 항목을 수정할려고 하니 어디에서 수정해야하는지 모르겠습니다. 혹시 수정폼에서 항목이 빠진건가요? 아니면 한번 생성하면 권한 설정이 불가능한건가요?

**Comment by oh4851** [comment]
@namineya 그룹생성폼에는 그룹명, 그룹설명 항목만입력받습니다.
말씀하신 공개 권한설정은 프로젝트생성, 관리에서 사용하는것같습니다.

확인부탁드릴께요^^

**Comment by namineya** [comment]
@oh4851 고맙습니다!
