### ISSUE TITLE
메일 발송 세팅 문제

### ISSUE THREAD

**Issue by company1234** [naver/yobi#832]
안녕하세요 네트워크 문제로 문의를 많이남기네요..

사설망인지라 외부 네이버/gmail smtp를 사용하지 못하고, 저희 사내 공인아이피 할당되어있는 곳에 sendmail 을 이용하여 변경하려고하는데

요비가 오픈소스가 아니다보니 제가 메일이 어떻게 날라가는지 로직을 보지 못하고 알고 있는 부분

이 conf/application.conf 에 smtp.... 으로 시작된 부분의 설정으로 메일을 발송한다 정도만 알고 있는

데요 사내 리눅스서에서 sendmail 구축하고 addUser로 메일계정 생성, 도메인 할당해서 conf파일에  

user, password , domain 등 세팅하면 되는것인지.. 궁금합니다.

**Comment by doortts** [comment]
네. 맞습니다. 그렇게 하시면 됩니다.
다만 포트를 몇 번으로 쓰실지 잘 정하시면 됩니다.
기본 sendmail port는 25 번을 많이 쓰고,
secure 로 쓰신다면 465 를 쓰시지 않을까 생각됩니다.

저희도 예전에 내부에서 sendmail 서버를 열어놓고 썼었습니다. : )

ps.
요비는 오픈소스입니다.... 쿨럭...

**Comment by company1234** [comment]
그러니까 application.conf의  smtp.user랑 smtp.domain과 smtp.password 는

sendmail 에서 세팅한 것과 유효한 것들이 들어가야한다는 말씀이신거죠?

**Comment by doortts** [comment]
네. 맞습니다.

application.conf 에서 
```
smtp.mock = false
```
로 고치는 것도 잊지마시고요.

**Comment by company1234** [comment]
sendmail이아닌 다른 메일발송로직을 추후 사용하게될것같아, 적용시켜보지 못했습니다.

**Comment by doortts** [comment]
나중에 해보시고 안되시면 다시 알려주세요~
