### ISSUE TITLE
기능 문의

### ISSUE THREAD

**Issue by company1234** [naver/yobi#833]
mantis /bts 대용으로 요비를 사용하려 하고있습니다.

현재는 열기/닫기 로 구분되더라구요

이 부분을 관리자가 단계를 수정할수 있다던지

권한도 관리자/ 사용자 두단계뿐인데 / 수정할수있게한다던지하는

기능이 있으면 좋을 거같은데 개발자분들 생각이 어떠신지 궁금합니다.

**Comment by doortts** [comment]
답변이 늦었습니다.

workflow 에 대한 의견이신것 같은데요, 사실 내부적으로도 workflow 있어야 한다는 목소리들이 있었습니다. 그런데 현재 custom label 을 이용해서 어느정도 수동으로 처리가 가능해서 우선순위가 뒤로 밀리고 있는 상황이긴 합니다.

저희도 이런저런 라벨을 이용해서 해당 부분을 처리하고 있고요.
아미 Yobi가 좀더 성숙해지면 해당 기능이 들어가지 않을까 생각합니다.

사용해 주시고 의견 주셔서 고맙습니다.
: )
