### ISSUE TITLE
내 이슈 보기 버그

### ISSUE THREAD

**Issue by hellobpm** [naver/yobi#838]
내 이슈 보기에서 다음 페이지 버튼 눌러서 이동하면 페이지 이동 버튼이 없어 지는 현사 있음.

**Comment by npcode** [comment]
Firefox 쓰시는지요?

**Comment by doortts** [comment]
@hellobpm 저도 파폭유저라 동일 문제를 겪고 있는데 조만간 해결될 예정입니다. pjax 관련 문제인데 로컬테스트에서는 원인과 해결책을 확인했습니다. 불편하시겠지만 조금만 기다려 주세요.

**Comment by insanehong** [comment]
f3d68d8c177917efd2b127b869736aceb5f138ff 에서 수정되었습니다.
