### ISSUE TITLE
centos 에서 yobi를 계속 켜놓을 수 있는 Service에 등록하려면 어떻게 해야하나요?

### ISSUE THREAD

**Issue by Reizeo** [naver/yobi#839]
play framework 말고는 답이 없나요??

**Comment by ddokkaebi** [comment]
1. /etc/init.d/jira 파일을 만들어서 yobi 실행 스크립트 작성
2. chkconfig --add jira 로 upstart에 등록해주시면 됩니다.
나머지는 파일권한 등등의 이슈만 잘 맞추면 부팅시에 자동으로 시작됩니다.

**Comment by akairain** [comment]
#!/bin/bash
# chkconfig: 345 20 85
# description: Yobi start/shutdown script
# processname: play
#
# Usage: (as root)
# service yobi start
# service yobi stop
# service yobi status

PLAY_PATH=/usr/local/play
PLAY_BIN=${PLAY_PATH}/framework/build

JAVA_HOME=/usr/java/jdk1.7.0_75
export JAVA_HOME

USER=root

APPLICATION_PATH=/usr/local/play/yobi
APPLICATION_MODE=prod
APPLICATION_PORT=80

. /etc/init.d/functions
RETVAL=0

start() {
	echo -n "Starting Yobi: "

	if [ -f ${APPLICATION_PATH}/RUNNING_PID ]; then
		echo "service already running!"
		echo_failure
	else
		su -s /bin/sh $USER -c "cd ${APPLICATION_PATH} && ${PLAY_BIN} \"start -Dhttp.port=${APPLICATION_PORT}\"" > /dev/null &
		RETVAL=$?

		if [ $RETVAL -eq 0 ]; then
			echo "Start request sent! Please wait for 30~60 seconds while started"
			echo "If you want to see log use command below."
			echo "tail -f ${APPLICATION_PATH}/logs/application.log"
			echo_success
		else
			echo_failure
		fi
	fi
	echo
}

status() {
	if [ -f ${APPLICATION_PATH}/RUNNING_PID ]; then
		echo "Yobi service already started"
	else
		echo "Yobi service not started"
	fi
}

stop() {
	echo -n "Shutting down Yobi: "
	if [ -f ${APPLICATION_PATH}/RUNNING_PID ]; then
		kill `cat ${APPLICATION_PATH}/RUNNING_PID` > /dev/null
		RETVAL=$?

		if [ $RETVAL -eq 0 ]; then
			echo_success
		else
			echo_failure
		fi
	else
		echo_failure
	fi
	echo
}
case "$1" in
	start)
	start
	;;
	stop)
	stop
	;;
	restart|reload|graceful)
	stop
	sleep 10
	start
	;;
	status)
	status
	;;
	*)
	echo "Ussage: $0 {start|stop|restart|graceful|reload|status}"
esac

제가 사용하는 Init Script 입니다.

**Comment by doortts** [comment]
@ddokkaebi 님 답변 고맙습니다!
해보시고 안되시면 다시 열어주세요.
