### ISSUE TITLE
서버이전시 백업관련 문의

### ISSUE THREAD

**Issue by l2zeo** [naver/yobi#840]
서버 이전시 프로젝트들 백업을 하려면 어찌해야 하는지 알려주시면 감사하겠습니다.

**Comment by doortts** [comment]
https://github.com/naver/yobi#%EB%B0%B1%EC%97%85%ED%95%98%EA%B8%B0
를 참고해 주세요.
새로운 곳에 새롭게 설치하신 다음에 위 링크의 파일들만 이전 한 곳에 덮어씌우시면 동일하게 운영가능합니다.

**Comment by l2zeo** [comment]
@doortts 감사합니다 .^^
