### ISSUE TITLE
이메일 발송시 도메인-ip 및 https 문제

### ISSUE THREAD

**Issue by ajkj** [naver/yobi#843]
nginx 를 이용하여 reverse proxy(ssl은 nginx decrypt)로 yobi를 사용하고 있습니다.
listen on 127.0.0.1:8001

한대의 서버에서 다수의 https를 돌리기에 SSL SNI를 이용중입니다.

이메일을 발송시 View it on Yobi 주소에 도메인이 들어가 있지 않고, 서버 IP주소가 들어가 있어서 이메일에서 View it on Yobi를 누르면 정상적으로 접속이 되지 않는 버그가 존재합니다.

http**s**://yobi.example.com 에서 이메일을 발송시

```
Accepted as a member.
--
View it on http://260.1.1.1/exampleproject/repo
```

이런식으로 https 링크도 적용되지 않고 도메인이 아닌 ip가 나오는 버그가 있습니다.

**Comment by ajkj** [comment]
nginx 를 이용하여 reverse proxy(ssl은 nginx decrypt)로 yobi를 사용하고 있습니다.
listen on 127.0.0.1:8001

한대의 서버에서 다수의 https를 돌리기에 SSL SNI를 이용중입니다.

이메일을 발송시 View it on Yobi 주소에 도메인이 들어가 있지 않고, 서버 IP주소가 들어가 있어서 이메일에서 View it on Yobi를 누르면 정상적으로 접속이 되지 않는 버그가 존재합니다.


http**s**://yobi.example.com 에서 이메일을 발송시

```
Accepted as a member.
--
View it on http://260.1.1.1/exampleproject/repo
```

이런식으로 https 링크도 적용되지 않고 도메인이 아닌 ip가 나오는 버그가 있습니다.

**Comment by ajkj** [comment]
x-forwared-proto 헤더가 set 되 있다면 application 설정의 https 보다 해당 header를 우선시 하는건 어떨까요?

**Comment by seyriz** [comment]
#791 이슈에 해결법이 나와있는것 같네요 저는 저렇게해서 잘 쓰고 있습니다

**Comment by ajkj** [comment]
이메일 키워드로 검색했는데 이상하게 검색이 안됬네요. 일단 이슈 닫을게요.
