### ISSUE TITLE
프로젝트 정보에 Language 설정

### ISSUE THREAD

**Issue by mangochicken** [naver/yobi#844]
프로젝트 정보에 Language 추가하는 거 있는데...
![language](https://cloud.githubusercontent.com/assets/10045979/5770055/02d001a4-9d68-11e4-816f-496f88081c38.JPG)
이게 뭔지 잘 모르겠어서 문의 드립니다~

**Comment by npcode** [comment]
그냥 다른 사람들이 이 프로젝트에서 어떤 언어를 사용하는지 알 수 있도록 라벨을 붙이는 것입니다.
