### ISSUE TITLE
admin 계정의 사이트 설정 버튼이 나타나지 않음.

### ISSUE THREAD

**Issue by KOR-Believer** [naver/yobi#846]
1. Play 2.1 + Yobi(Master) 의 경우 admin 로그인 시 정상적으로 사이트 설정 버튼이 나타나는데
2. Play 2.3 + Yobi(Next)에서 admin 로그인 시 사이트 설정 버튼이 나타나지 않습니다.

__usermenu.scala.html__
```
@if(session.get("userId").equals("1")) {
    <li class="gnb-usermenu-item">
        <a href="@routes.SiteApp.userList()" data-toggle="tooltip" title="@Messages("menu.siteAdmin")" data-placement="bottom" class="usermenu-icon-button">
            <i class="yobicon-wrench"></i>
        </a>
   </li>
}
```
이 부분에서 `@if(session.get("userId").equals("1")) ` 문제가 있는 것 같습니다.
Before(1.)
![before](https://raw.githubusercontent.com/KOR-Believer/git-study/master/image/bef.PNG)

After(2.)
![after](https://raw.githubusercontent.com/KOR-Believer/git-study/master/image/aft.PNG)

**Comment by npcode** [comment]
Play 2.3으로 올라가면서 문제가 생긴 모양이군요.

**Comment by npcode** [comment]
81f4d538d9264e09724e21cb76422ff450e82fd4 에서 고쳤습니다.
