### ISSUE TITLE
Pull Request에서 1명이 2번 review할 수 있는 버그

### ISSUE THREAD

**Issue by dythmall** [naver/yobi#847]
pull request에서 2번의 review를 받아야 머지되 도록 세팅함.
pull request를 하고 한명이 'Reviewed' 버튼을 '따닥'하고 두번 누르면,
한 사람이 2번 리뷰한 것으로 나오고 머지가 가능함.

**Comment by keesun** [comment]
앗 이거 고쳐야 하는 버그인데.. 깜빡하고 있었네요.
곧 고치겠습니다.
버그 리포팅 감사합니다.

**Comment by dythmall** [comment]
./app/models/PullRequest.java
에서 
public List<User> reviewers = new ArrayList<>();
를 Set으로 바꾸면 근본적으로 해결되지 않을까 생각합니다.
어차피 reviewer에 같은 User가 2번 들어가지 못하니까요.
문론 User의 hashCode()랑 equals()를 override해줘야 겠죠 HashSet을 쓰려면.

**Comment by keesun** [comment]
넵 맞습니다 풀리퀘를 보내주셔도 되겠는데요 해주시겠어요? ㅎㅎ

—
Keesun Baik백기선

**Comment by dythmall** [comment]
제가 User쪽 hashCode랑 equals를 만들 여력은 안되고 (또한 이 함수는 정책을 어떻게 하느냐에 따라 달라지는 함수들이니까요), PullRequest.java의 Pull Request 를 만들께요,
User.java의 hashCode를 좀 만들어 주시면 좋겠어요.

**Comment by keesun** [comment]
User쪽에 hashCode랑 equals는 id랑 loginId 프로퍼티로만 만들어도 괜찮을 것 같습니다.

둘 다 User마다 고유하며 중복을 허용하지 않고 반드시 입력해야 하는 값이니까요. 

괜히 다른 프로퍼티까지 많이 사용해봤자 연산만 더 오래 걸리뿐이겠죠. (그래도 얼마 안걸리긴 하겠지만)

실제 함수를 구현하는건 IDE에서 사용할 프로퍼티만 선택하면 뚝딱뚝딱 해줄겁니다.




PullRequest와 User까지 잘 부탁드려요!




감사합니다.











—
Keesun Baik백기선

**Comment by dythmall** [comment]
두개만 사용하면 된다면 뭐.. 
네, 우리 팀이 고맙게 잘 쓰고 있는 프로젝이라 감사한 마음에서 제가 만들께요 ㅎㅎ

**Comment by keesun** [comment]
감사합니다. 풀리퀘 보내주시면 리뷰 할께요! :)


—
Keesun Baik백기선

**Comment by dythmall** [comment]
pull request #848
