### ISSUE TITLE
Failed to get local hostname

### ISSUE THREAD

**Issue by restart916** [naver/yobi#852]
start 실행시 위와 같은 에러가 나옵니다다

23:45:19,480 |-ERROR in ch.qos.logback.core.util.ContextUtil@468cfbb6 - Failed to get local hostname java.net.UnknownHostException: xxx: xxx: 이름 혹은 서비스를 알 수 없습니다
	at java.net.UnknownHostException: xxx: xxx: 이름 혹은 서비스를 알 수 없습니다
	at 	at java.net.InetAddress.getLocalHost(InetAddress.java:1473)
	at 	at ch.qos.logback.core.util.ContextUtil.getLocalHostName(ContextUtil.java:32)
	at 	at ch.qos.logback.core.util.ContextUtil.addHostNameAsProperty(ContextUtil.java:41)

여기서 관련 에러를 찾아보고는 있는데 해결방법을 잘 모르겠네요
/etc/hosts 에는 아래와 같은 내용이 있습니다.
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

ncloud 서버를 사용하고 있으며 
centos-6.3-64 에 java만 1.7버전으로 업데이트한 상태입니다.

**Comment by npcode** [comment]
[JDK 7 버그](http://jira.qos.ch/browse/LOGBACK-749)인 것 같네요. logback 쪽에선 우회해서 해결한 모양인데, Yobi v0.7.x는 Play 2.1을 쓰고 있어서 logback도 이 문제를 우회하지 못한 버전일 것 같네요. 추후 v0.8.0(현 next 브랜치)을 사용하시면 해결될 것입니다.

**Comment by restart916** [comment]
네 감사합니다.

master 말고  next 브랜치를 사용하면 된다는 말씀이시죠?
해당 브랜치로 가져와서 해보도록 하겠습니다.

**Comment by npcode** [comment]
@restart916 next 브랜치는 Play 2.3을 쓰고 있어 시작 방법이 다르니 README.md를 먼저 확인해 보셔야 할 것입니다.

**Comment by npcode** [comment]
@restart916 docs/relnotes/0.8.0.txt 에 적혀있는 backward compatibility notes도 참고하셔서 설정 수정도 하셔야 할 것입니다.

**Comment by restart916** [comment]
시간이 오래걸렸네요. 결국 성공했습니다. (git 콘솔력이 부족해서 next 브랜치를 따오는데 고생했네요)

[error] n.s.e.Cache - Unable to set localhost. This prevents creation of a GUID.
[error] application - Failed to open IMAP folder

두개 에러가 나오긴 했지만 요비 첫페이지를 보는데 성공했습니다. 감사합니다.
