### ISSUE TITLE
Sending notification mail to the unregistered members...

### ISSUE THREAD

**Issue by krifle** [naver/yobi#853]
For instance if my Yobi ID is naver.com,
and someone else has inserted a new issue to some other project (which I'm not registered) with email addresses in content.

=====

Blah blah
asdf@naver.com
blah blah

=====

Then Yobi's NotificationEvent class will parse the content and understand that email address as a mention to me...
Problem is that I'm not registered to that project nor have an access to it, but I'm getting all the email notifications with the full contents and discussions in it.
This would be a major security issue...

**Comment by npcode** [comment]
Yobi don't make a link to a mentioned  user if there is non-whitespace character just before the '@' character since 11db69496ab537b88f4a519199918cd8a7ad12ff.

The commit is in next branch and v0.8 will contain the fix.
