### ISSUE TITLE
github처럼 zip로 프로젝트 다운로드 가능하도록 제안 드립니다

### ISSUE THREAD

**Issue by yongbeam** [naver/yobi#856]
#702 에서 github 처럼 프로젝트를 압축해서 다운로드할 수 있는 기능이 추가될 예정이라고 해주셨는데요
언제쯤 추가되는건가요?
너무 고픈기능이에요ㅠ

**Comment by npcode** [comment]
#499 에 댓글로 의견 부탁드립니다.

**Comment by doortts** [comment]
@yongdec v0.9 pre-meeting 에서 이거 구현하자고 멤버들이 이야기했습니다. 너무 미뤘네요..
