### ISSUE TITLE
시작시 한글로 보이게 할려면 어떻게 해야하나요?

### ISSUE THREAD

**Issue by haramnara** [naver/yobi#859]
시작시 한글로 보이게 할려면 어떻게 해야하나요?

영문으로 다 나오는데 ㅠㅠ;;

**Comment by insanehong** [comment]
사용하시는 OS와 Browser 정보를 알려주시면 더 자세한 안내를 해드릴수 있을거 같습니다. 

기본적으로는 브라우저에서 설정된 언어우선순위를 따르고 있습니다.

**Comment by pokev25** [comment]
@haramnara IE말고 다른 브라우저 사용하세요. IE 에서만 그럴껍니다.

**Comment by npcode** [comment]
웹브라우저에서 선호 언어를 대한민국 한국어(ko-KR) 대신 한국어(ko)로 하시면 문제없을 것입니다.

관련이슈: #757
