### ISSUE TITLE
jenkins git Repository URL에 주소를 넣으면 에러가 납니다.

### ISSUE THREAD

**Issue by daye** [naver/yobi#860]
Failed to connect to repository : Error performing command: /usr/local/git ls-remote -h http://sklee@주소:9999/planning2team/iccs HEAD returned status code 128:
stdout: 
stderr: fatal: Unable to find remote helper for 'http'

Credentials에 아이디 패스워드를 넣을경우
Failed to connect to repository : Could not init /usr/local/tomcat/temp/hudson3091849502693678995tmp

**Comment by npcode** [comment]
비공개 저장소인가요? 비밀번호가 없어서 에러가 나는 것이 아닌가 싶은데요.

**Comment by npcode** [comment]
jenkins 서버에 설치된 Git이 http를 사용할 수 없도록 되어있는 것 같네요. 확인부탁드립니다.

**Comment by daye** [comment]
git clone: fatal: Unable to find remote helper for 'https' 이런에러가 날떄 밑에 주소를 참고 하시면 해결 될듯 하네요 문제는  curl-devel이게 설치가 안되서 그런거네요

http://stackoverflow.com/questions/8329485/git-clone-fatal-unable-to-find-remote-helper-for-https
