### ISSUE TITLE
docker image생성해둘 순 없나요?

### ISSUE THREAD

**Issue by thinkong** [naver/yobi#862]
docker 로 배포 할 예정은 없으신가요?

하나하나 설치하는것보단.. 이것이 더 편하고 빠를수도 있을꺼라고 생각이 됩니다만..

**Comment by doortts** [comment]
저희가 docker를 쓸줄 모릅니다... ;;; 죄송합니다.
다만 조만간 있을 0.8에서 dist (배포) 버전을 따로 제공하려고 테스트 하고 있습니다.

**Comment by thinkong** [comment]
@doortts 
앗 배포버젼 기대하고 있겠습니닷!!

**Comment by npcode** [comment]
Play 2.3 부터는 activator docker:publishLocal 로 도커 이미지 생성 가능한 모양이네요.
