### ISSUE TITLE
터미널 접속을 종료하면 플레이 프레임워크가 죽어버립니다

### ISSUE THREAD

**Issue by TaeSeong** [naver/yobi#863]
안녕하세요. yobi관련 이슈는 아닌데 여쭈어 볼 수 있는곳이 없다보니 이곳에 이슈를 올리게 되었습니다

호스팅 받던 가상서버에 yobi를 설치하여 사용하다가 개인서버를 들여놓게 되어서

거기에 yobi를 설치하려고 하던중에 서버 환경의 문제인지

터미널에 접속해서 플레이 프레임워크를 실행하고

터미널 접속을 종료하면 플레이 프레임워크가 죽어버리네요

os가 일반 리눅스가 아닌 시놀로지 dsm을 x86서버에 설치한것인데 이게 원인일까요?

http://youtu.be/Lg2mEA4h8Kw
해당 증상을 영상으로 캡쳐해보았습니다.

**Comment by doortts** [comment]
네. 우선 자세히 녹화해 주신 재현 영상은 잘 봤습니다.
실행후 ctrl-d 로 콘솔로 빠져나간 다음에도 정상적으로 잘 되는 데 터미널 접속을 종료하니 죽어버리다니 좀 충격적이네요.

명령줄을 한번에 실행하고 nohup을 붙여서 해보시면 어떨까요?

```
nohup ../play start -DapplyEvolutions.default=true -Dhttp.port=9999 &
```

**Comment by npcode** [comment]
Ctrl+d로 빠져나갔다면 Yobi 프로세스의 부모가 init이 되어야하는데, 여전히 쉘이 부모인 상황이 아닌가 싶네요. Ctrl+d로 빠져나간 후의 Yobi 프로세스(java)의 부모 pid가 어떻게 되나요? 

부모 pid는 아마 다음과 같은 방법으로 얻을 수 있을 것입니다.

```
ps -p `cat RUNNING_PID` -o ppid=
```

**Comment by TaeSeong** [comment]
@doortts  nohup을 이용해서 실행해도 동일한걸로보아 시스템에서 죽이는게 아닌가 싶네요
@npcode ppid를 얻고 싶은데 알려주면 커멘드로는 확인할 수 없는거 같네요

일단 두분께서 알려주신 내용을 토대로 확인해봐야겠습니다

**Comment by TaeSeong** [comment]
터미널을 통해 원격으로 접속하지않고 서버에서 바로 play를 실행하는걸로 해결하였습니다
서버에서 바로 실행하니 끊어질일이 없네요
답변해주신분들 정말 감사드립니다. :)
