### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by tunz** [naver/yobi#865]
1.
`http://yobi-url/ID/REPO/code/master#<img src='x' onerror='alert(1)'>`
해당 URL로 접속했을때.

2.
마일스톤에 `<img src=x onerror=alert(1)>` 로 이름을 만들고나서,
다른곳(이슈 등)에서 마일스톤을 선택할때.

그리고 추가로 공격은 불가능할거 같긴한데
1. markdown에서 `<img src=x onerror=alert(1)>`를 입력하고, 미리보기를 할때
2. 파일명을 `<img src=x onerror=alert(1)>`로 업로드한 순간
도 스크립트 실행이 되긴 하네요.

**Comment by doortts** [comment]
제보 감사합니다!

**Comment by insanehong** [comment]
39fab7167f686bfe1ac653304545ee3a83fddc84 에서 수정 되었습니다.
