### ISSUE TITLE
yobi에 도메인 설정을 하려고 합니다.

### ISSUE THREAD

**Issue by mango-i** [naver/yobi#870]
안녕하세요.
yobi에 도메인 설정을 하려고 하는데 현재 사용하고 있는 os는 우분투이고 웹서버는 apache입니다.
yobi는 Play라는 것으로 서버를 구동시키던데 이 자체에서는 서버네임을 설정할 수 있는 방법이 없는건가요? 아니면 apache proxy를 사용해야하는지 궁금합니다.

**Comment by npcode** [comment]
Virtual Hosting을 하시려는 것인가요?

**Comment by mango-i** [comment]
@npcode 네 가상호스트로 설정할 생각입니다.

**Comment by npcode** [comment]
@mango-i 네 그렇다면 apache등으로 proxy를 구성해야합니다.

**Comment by mango-i** [comment]
@npcode 아 그렇군요 감사합니다
