### ISSUE TITLE
이슈 댓글에 대한 권한이 이상한 것 같습니다

### ISSUE THREAD

**Issue by gladsky-park** [naver/yobi#871]
비공개 프로젝트 이슈에서 다른 사용자가 작성한 댓글을 수정할 수 있더군요.
홈페이지나 블로그 사용 개념에서는 본인이 작성한 것은 본인만 수정이 가능한데
요비에서는 원래 취지인 것인지 궁금합니다.

**Comment by gladsky-park** [comment]
기존에 이슈가 있었던 내용이네요... 제가 작성한 이슈 삭제는 어떻게 하나요?

**Comment by doortts** [comment]
@gladsky-park 그냥 닫아주시면 됩니다. : )
