### ISSUE TITLE
Svn사용모드에서 커밋 히스토리(변경이력) 문제입니다.

### ISSUE THREAD

**Issue by kimorkim** [naver/yobi#875]
저장소를 SVN으로 만들고 사용중인데.

특정코드를 열고 변경이력을 누르면 

커밋 히스토리 목록가지는 나오는데 여기서 파일 보기를 누르면

"페이지를 찾을 수 없습니다"
 "홈"

이라고 표시 됩니다.

**Comment by npcode** [comment]
모든 파일에 대해서 그러한가요?

**Comment by kimorkim** [comment]
네 모든 파일에서 그러는것 같습니다. 버전은 0.7.3 최신버전이고

윈도우 7 32비트 환경에 설치 했습니다.

**Comment by npcode** [comment]
윈도라서 그런 것 같네요. Yobi가 디코딩을 할 때 시스템 locale에 지정되어있는 charset을 사용하고 있었는데 그것 때문에 문제가 생긴게 아닐까 싶어요.

이 문제는 ac83c23715cd4632ed43faca3250a037bebc89ae 에서 플랫폼과 상관없이 항상 UTF-8을 사용하도록 고쳐졌습니다.

**Comment by npcode** [comment]
아 파일 이름이 한글인가요?

**Comment by kimorkim** [comment]
아니요 확인한 파일이름은 영문 입니다.

**Comment by npcode** [comment]
그럼 다른 문제군요

**Comment by kimorkim** [comment]
참고로 커밋히스토리 에서 리비전 번호가 좌측에 @ 로 나오던데 이걸 클릭하면 

해당 리비전의 모든 코드들은 잘나옵니다. 특정 파일만 안나오네요 흠..

**Comment by npcode** [comment]
원인은 커밋 아이디를 제대로 넘겨주지 못해서인데요. 해결이 간단하진 않네요.
