### ISSUE TITLE
milestone 기능 문의

### ISSUE THREAD

**Issue by kimjuik** [naver/yobi#879]
milestone 기능이.. UI 상으로는 왠지 세부 task를 입력하고 각 task 별로 완료를 체크해서 전체 진행도를 알 수 있는 것 처럼 생겼는데..

현재는 큰 제목만 입력할 수 있네요. 이게 현재 상태인건가요? 아니면 제가 뭔가 설치를 잘못한 걸까요..

현재 설치장소는  http://service.magicboy.net:9000/ 에서 돌고 있습니다~

**Comment by insanehong** [comment]
안녕하세요 마일스톤의 경우 이슈를 할당할수 있습니다. 

이슈메뉴에서 새이슈를 등록하거나 기존 등록된 이슈를 수정하실때 마일스톤을 지정할 수 있습니다.
