### ISSUE TITLE
Yobi의 웹 루트 경로 수정이 가능한가요?

### ISSUE THREAD

**Issue by jangbi882** [naver/yobi#881]
Apache Proxy를 이용해 다른 서비스들과 80 포트로 묶어서
http://localhost/yobi 로 호출하면 yobi가 서비스되게 하고 싶습니다.

초기 페이지는 포워딩으로 정상적으로 보이는데
/assets, /user 등 많은 경로가 절대경로로 되어 있어 기능이 정상 동작 하지를 않는군요.

혹시 play로 실행할 때부터 웹루트 경로를 /yobi 등으로 바꿀 수 있는 방법이 있는지요?

**Comment by npcode** [comment]
application.conf에서 application.context="/yobi"로 설정해주시면 어느정도 될 것입니다.
