### ISSUE TITLE
라벨를 모든 프로젝트 동일하게 등록하고 싶습니다.

### ISSUE THREAD

**Issue by l2zeo** [naver/yobi#889]
프로젝트가 많아지면서 라벨를 일일이 추가해야 하는데요.
전체모두 적용 같은부분이 필요할거 같습니다.
은근 노가다네요 ㅠ.ㅠ

**Comment by doortts** [comment]
안녕하세요?
내부에서도 비슷한 의견들이 있었는데요 혹시 다른 프로젝트의 라벨을 통째로 복사하는 기능이 생기면 도움이 될까요?

**Comment by l2zeo** [comment]
말씀주신거처럼 다른 프로젝트의 라벨를 복사하는 기능이 있다면 좋을거 같습니다.^^

**Comment by doortts** [comment]
답변감사합니다. 다음 릴리즈에는 해당 기능이 포함될수 있도록 멤버들이랑 함께 작업해 보겠습니다.

**Comment by l2zeo** [comment]
감사합니다.
