### ISSUE TITLE
알림메일 발송 관련 문의

### ISSUE THREAD

**Issue by rooneypark** [naver/yobi#893]
계정 > 설정 > 이메일 설정 > 추가 > 메일 계정 추가 > 확인 메일 전송 했을 시에는

등록한 smtp에 등록한 메일 이름으로 설정 추가된 메일 계정에 메일이 보내집니다.

하지만,  게시글, 이슈 등을 등록 시 해당 메일이 오지 않아서 문의 드립니다.

아래 제가 설정한 부분입니다. 
application.conf
-----------------------------------------------------------
smtp.host = smtp.gmail.com
smtp.port = 465
smtp.ssl = true
smtp.user = mygmailID <-- @gmail.com 은 제외
smtp.password = mypassword
smtp.domain = gmail.com
smtp.mock = false
smtp.archive.size = 5
------------------------------------------------------------

**Comment by keesun** [comment]
이슈, 게시물 등에 대한 알림을 받고 싶으시다면 알림을 받고 싶은 프로젝트나 각 이슈 또는 게시물을 `지켜보기` 하셔야 하는데요.

혹시 특정 프로젝트를 지켜보기 하셔도 알림이 오지 않나요?

**Comment by rooneypark** [comment]
네 지켜보기를 해도 알림이 오지 않습니다.

다른 부분 설정해줘야 되는 부분이 있나요?

**Comment by rooneypark** [comment]
제대로 동작 되는 것 확인 하였습니다. 이슈 클로즈하겠습니다.
