### ISSUE TITLE
commit 시 auto close

### ISSUE THREAD

**Issue by alzkdpf** [naver/yobi#894]
github 나 redmine 처럼 commit 시 close #number 하면
이슈 닫기 할 수 없을까요?

**Comment by doortts** [comment]
해당 기능은 예전에 논의되었던 부분인데요 우선순위에 밀려있는 상태입니다. 혹시 contribution 의향 있으시다면 지점을 알려드릴 의향이 있습니다.  그리고 contribution 패키지도 보내드려요. : )

**Comment by alzkdpf** [comment]
contribution 해드리고 싶지만 playframework 쪽은 경험이 전무해서 ^^;;;
