### ISSUE TITLE
코드 레포지토리에 용량 제한 같은 것이 있나요?

### ISSUE THREAD

**Issue by youngjinkim0706** [naver/yobi#895]
안드로이드 전체 프레임워크를 올려보려고 했는데 (약 30gb)
올리는 용량에 제한이 있는지요
혹시 있다면 한도를 늘릴 수 있는 방법도 있을까요?

**Comment by doortts** [comment]
git 저장소 사이즈에 특별한 제한은 없습니다.  참고로 이슈나 게시판 등에서 파일업로드시에는 단일 파일 2g로 제한되어 있습니다.

**Comment by npcode** [comment]
그 정도 크기라면 clone 할 때 시간이 매우 많이 걸릴 수 있습니다. 그런 경우에는 --depth 옵션을 이용해 shallow clone 하시면 됩니다. (`git clone --depth 1` 정도)

JGit이 좀 느려서 그런건데, 구글에서도 그런 경우엔 그냥 shallow clone 하는 모양이더군요.

**Comment by youngjinkim0706** [comment]
답변 감사합니다!
