### ISSUE TITLE
데이터를 따로 관리하고 싶습니다.

### ISSUE THREAD

**Issue by woomg** [naver/yobi#896]
Debian에 OpenMediaVault를 설치하고 Yobi를 설치를 했습니다.
프로그램을 데이터 파티션(폴더)에는 설치를 할 수가 없습니다. 기본적으로 데이터 파티션에는 noexec 속성이 걸려있어서 프로그램 설치를 할 수 없습니다.

현재 기본값으로 설치를 하면 시스템 파티션에 설치가 되고 .../play-2.1.0/yobi/repo에 코드 리포지토리가 형성이 되는데요, 별도의 데이터 파티션의 공유폴더(/media/uuid-code/shared/)에 코드와 게시판 DB등 데이터를 관리하고 싶습니다.

설정값을 몰라서 일단 repo는 데이터 파티션의 데이터 폴더에 심볼릭 링크를 걸었는데요...
게시판 DB와 리포지토리 모두 데이터 파티션의 데이터 폴더를 지정할 수는 없을까요?

**Comment by npcode** [comment]
v0.8에서 분리가 가능해질 예정입니다. 그때까지는 심볼릭 링크로 하셔야 할 것 같습니다.

**Comment by npcode** [comment]
v0.8 릴리즈되었습니다.
