### ISSUE TITLE
라벨추가시 버그 알려드립니다.

### ISSUE THREAD

**Issue by alzkdpf** [naver/yobi#897]
0.7.3 버전이고
기존 라벨이 하나 존재한 상태에서 새 라벨을 추가하고 색상값을 적용한 다음 추가하면
값은 정상적으로 들어가는데 색상값은 기존 라벨과 똑같은 값으로 들어가내요.

동일한 방법으로 2,3개 만들어봤는데 컬러값이 지정한 값이 아닌 기존에 존재했던 라벨의
컬러값으로 들어갑니다. 

생성후 수정은 정상적으로 처리됩니다.

**Comment by npcode** [comment]
@insanehong 혹시 bc8bb6f073e079beb5e0853ec9a16513b6a87762 가 이 문제를 고쳐주나요?

**Comment by alzkdpf** [comment]
확인해 봤는데 안돼내요. ㅜ.ㅜ 분류가 존재하지 않는 라벨은 색상값이 정상적으로 적용되는데 분류가 존재하는 라벨은 처음 등록한 라벨 색상값 기준으로 적용되고 수정을 통해서만 새 색상값이 등록되내요.

**Comment by insanehong** [comment]
@npcode  fedd18f 이 커밋에서 수정 되었습니다.

**Comment by alzkdpf** [comment]
오홍~ 패치 후 잘되내용 감사합니당.~
