### ISSUE TITLE
라벨 일괄 적용 기능 요청

### ISSUE THREAD

**Issue by hellobpm** [naver/yobi#900]
이슈 리스트에서 다건 선택하여 라벨 일괄 적용할 수 있는 기능이 있으면 도움이 될거 같습니다.

**Comment by doortts** [comment]
![hive 2015-05-12 11-46-57](https://cloud.githubusercontent.com/assets/520523/7579299/aed671ba-f89c-11e4-9022-d351c97ac80f.png)

안녕하세요? 현재 일괄적용 기능이 존재합니다.
목록에서 이슈를 체크박스로 선택하신다음 상단의 dropdown 메뉴를 이용하시면 됩니다.

**Comment by hellobpm** [comment]
해당 프로젝트 라벨 설정이 안 되어 있어서 안 보였던 거네요 ^^
감사합니다.
