### ISSUE TITLE
커밋 실패

### ISSUE THREAD

**Issue by zepinos** [naver/yobi#901]
116메가의 PSD 파일(파일명: 로그인화면2_2차.psd) 파일을 커밋하려고 했으나 반응이 없습니다.

TortoiseSVN (TortoiseSVN 1.8.11, Build 26392 - 64 Bit) 에서는 Timeout 이 발생하고, CollabNetSubversion-client-1.8.13-1-x64 을 이용한 TUI 에서의 commit 시에는 한시간 넘게 반응이 없습니다. (내부망이라 전송하는데 수분이면 될 것입니다) 이 때 yobi 콘솔에는 아래와 같은 에러가 발생합니다.

```
 2015-05-13 14:15:28,412 - [ERROR] - from application in Thread-3331 
org.tmatesoft.svn.core.SVNException: svn: E175007: Path '/로그인화면2_2차.psd' you requested not found
        at org.tmatesoft.svn.core.inte
```

프로젝트는 신규로 생성해서 체크아웃한 뒤 커밋해봤으나 마찬가지입니다.

yobi 실행 옵션은 아래와 같습니다.

```
start -DapplyEvolutions.default=true -Dhttp.port=80
```

**Comment by npcode** [comment]
같은 이름의 파일이라도 크기가 작으면 문제없이 커밋이 되는지요?

**Comment by zepinos** [comment]
네. E175007 오류는 찍히는데 올라가긴 합니다.

**Comment by npcode** [comment]
혹시 Yobi 서버에 직접 들어가셔서 localhost로 커밋하실 수 있나요? 네트웍 영향이 있는지 확인하기 위함입니다.

**Comment by npcode** [comment]
일단 저의 경우에는 150메가짜리 바이너라 파일이면 2분정도 시간이 걸리긴 하지만 정상적으로 커밋이 되고 있습니다.

**Comment by zepinos** [comment]
서버(CentOS 6.6, 2.6.32-504.16.2.el6.x86_64)에 들어가 svn(subversion-1.6.11-12.el6_6.x86_64)을 이용해서 http://localhost... 형식으로 checkout 받은 뒤 commit 해도 동일한 증상입니다.

**Comment by zepinos** [comment]
이유를 알 것 같습니다.

위에 언급했듯이 옵션에 별다른 메모리 옵션을 안줬는데, 메모리 옵션을 주니 용량 큰 것도 올라가네요.

파일 크기 때문에 메모리 옵션을 크게 잡아야 할 것 같은데...보통 -Xmx 을 2GB 이상 안잡는게 보통인데...파일이 수백메가씩 되면 매우 크게 잡아놔야 할까요?

현재 제가 구축한 머신도 가상머신이라 2GB 만 메모리를 할당해놨는데, 좀 더 크게 늘려놔야겠네요.

신경써주셔서 고맙습니다.

**Comment by npcode** [comment]
제보 감사합니다. 이건 faq로 문서화를 할 필요가 있을 것 같네요.

**Comment by doortts** [comment]
@zepinos 문제가 생긴 시점에서는 특별히 메모리 옵션을 주지 않고 띄우신 경우이신거죠?

**Comment by zepinos** [comment]
@doortts 네.
