### ISSUE TITLE
linux ssh 질문입니다.

### ISSUE THREAD

**Issue by kshhaja** [naver/yobi#902]
현재 넷북 주분투에 요비를 설치해서 사용하고 있습니다.

넷북 사양이 낮고, 서버를 3개 굴리다보니

자주 골로 갑니다. 조만간 하나 새로 장만할 거긴한데 그 전까지 작업은 계속 해야돼서요.

골로 갈때마다 제가 방에 있는건 아니라서

안드로이드로 터미널을 사용하여 ssh 접속을 해서 서버를 껏다 켜는데요.

백그라운드로 돌아가게끔 할 수 있는 방법 좀 알려주십시오...

모바일 인터넷이 끊기면 ssh도 같이 끊겨서 터미널이 꺼짐과 동시에 

서버도 같이 꺼집니다. 그래서 집 밖이면 핸드폰으로 이렇게 하고 

집에가서 다시 켜요... 이런 번거러움을 줄여줄수있는 방법 좀 알려주세요.

**Comment by npcode** [comment]
play start하고 ctrl+d로 나가도 ssh 끊기면 yobi가 같이 죽나요?

**Comment by kshhaja** [comment]
아.. 되네요. 감사합니다.
저는 Ctrl d가 EOF를 반환해서 프로세스가 꺼지는건줄 알았는데 살아있네요
