### ISSUE TITLE
0.7.3에서 0.8 업그레이드 중 오류 문의

### ISSUE THREAD

**Issue by yongseokleecom** [naver/yobi#913]
안녕하세요. 
이번 0.8 업그레이드 과정중에 문제가 생겼습니다. 몇번 재시도 했으나 실패하여 이슈기록합니다.

OS: Ubuntu 14.04.2 LTS
Java: 1.7.0_80

```
[error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: null.Message:Unique index or primary key violation: "PRIMARY KEY ON """".PAGE_INDEX"; SQL statement:
ALTER TABLE PUBLIC.ISSUE_COMMENT_VOTER ADD CONSTRAINT PUBLIC.FK_ISSUE_COMMENT_VOTER_ISSUE FOREIGN KEY(ISSUE_COMMENT_ID) REFERENCES PUBLIC.ISSUE_COMMENT(ID) NOCHECK [23505-176]
Oops, cannot start the server.
```

**Comment by npcode** [comment]
h2database 1.3.176의 버그인 것 같네요. https://groups.google.com/forum/#!msg/h2-database/LfJX1m2h56g/533vOn5KjMMJ

DB 백업해두시고, http://www.h2database.com/html/advanced.html#using_recover_tool 에 나온 방법대로 DB를 복원해서 한번 시도해보시겠어요?

**Comment by yongseokleecom** [comment]
복원 시도해보겠습니다. 
https://github.com/naver/yobi/issues/872#issuecomment-77801294
해당 코멘트에 좀더 상세한 사용법이 있내요.

**Comment by npcode** [comment]
restore/runscript 대신 script/runscript 하는 방법을 써 보심이 좋겠습니다. DB 업그레이드시 문제가 생길때는그렇게 하는 쪽이 정석인 것 같네요. 하는 방법은 http://www.h2database.com/html/tutorial.html#upgrade_backup_restore 에 나와있습니다.

**Comment by yongseokleecom** [comment]
@npcode 
도움주신덕분에 0.7.3 에서 0.8로 업그레이드 했습니다.
그런데 저의 경우 script/runscript 작업하니 h2.db 생성은 문제 없었으나, 기동시 오류가 발생했습니다.
restore/runscript 작업하여 마이그레이션 완료했습니다.
용량또한 차이가 발생합니다.

![2015-06-04 2 15 44](https://cloud.githubusercontent.com/assets/12702163/7966526/a4d2419c-0a5f-11e5-9873-484aabe65fdf.png)
yobi.h2.sql.Script >> yobi.h2.db.Script - script/runscript 사용
yobi.h2.sql.Recover >> yobi.h2.db- restore/runscript 사용

감사합니다.
