### ISSUE TITLE
코드 주고받기 기능 문의

### ISSUE THREAD

**Issue by WooJin-Jeon** [naver/yobi#918]
코드 주고받기에서 리뷰어를 지정하는 기능이 있나요?
예를 들어 관리자 레벨만 리뷰할 수 있고 코드를 병합할 수 있도록 하는 기능입니다.

**Comment by npcode** [comment]
리뷰어 지정 기능은 v0.9 혹은 v1.0 쯤에 들어갈 것 같습니다.

현재 리뷰는 프로젝트에 접근할 수 있는 사람이라면 누구나 할 수 있고, 머지는 프로젝트 멤버라면 누구나 할 수 있습니다.

**Comment by WooJin-Jeon** [comment]
네 감사합니다.
