### ISSUE TITLE
#455 버그 재현

### ISSUE THREAD

**Issue by boeunseo** [naver/yobi#922]
YOBI에서 GIT저장소의 소스를 사용중입니다.

예전 이슈 #455 가 비슷했던 증상같은데.. YOBI웹에서는 특정 폴더 밑에 있는 소스들이 보이지 않습니다.
저장소에서 새로 다운받으면 폴더 안의 내용까지 모두 다운로드되는걸로 봐선, 저장소에는 존재하구요.

이 증상 뭘까요ㅠㅠ

**Comment by npcode** [comment]
1. 디렉토리를 클릭하면 내용이 비어있나요 아니면 에러가 발생하나요?
2. 디렉토리 전체 경로명이 어떻게 되는지요?

**Comment by boeunseo** [comment]
1. 디렉토리를 클릭하면 내용이 비어있습니다. (에러 발생하지 않음)
2. 전체 경로명이 3MP.open-portal/app/components 입니다. ( components가 해당 디렉토리입니다..)

**Comment by boeunseo** [comment]
사유는 모르겠으나 작업하다보니 다시 보이기 시작합니다..;;
이슈 close 하겠습니다.
