### ISSUE TITLE
git push에 발생하는 경고

### ISSUE THREAD

**Issue by welikeheon** [naver/yobi#930]
안녕하세요?

yobi에 git 프로젝트를 업로드 할 때 이런 오류가 발생합니다.

RPC failed; result=22, HTTP code = 505

스스로 해결해보고 싶었는데 도저히 찾을 방법이 없어 이렇게 이슈 올립니다.

![2015-06-17 4 15 07](https://cloud.githubusercontent.com/assets/8732888/8192277/ef7d38a8-14a7-11e5-8708-4d01c3d89986.png)

위의 사진은 git 업로드할때 발생하는 오류입니다.

![capture](https://cloud.githubusercontent.com/assets/8732888/8192307/1d1e2c86-14a8-11e5-9f7d-20e4b408ac5e.JPG)

위의 사진은 서버 로그입니다.

nginx 에서 설정이 잘못 되었나 싶어 혹시나 하는 마음에 nginx 설정도 올립니다.

![2015-06-17 4 21 34](https://cloud.githubusercontent.com/assets/8732888/8192343/661f0aae-14a8-11e5-8b01-5902810f98b5.png)

파일이 많은 프로젝트를 올려봤는데요. 그건 아예 올라가지 않습니다.
그리고 테스트로 아무거나 입력하고 push 했을때는 같은 오류가 생기지만 올라가긴 합니다.

답변에 미리 감사인사드립니다.

**Comment by npcode** [comment]
505 HTTP Version Not Supported는 서버가 지원하지 않는 버전의 HTTP 프로토콜로 클라이언트가 요청을 보냈을 때 발생하는 에러입니다.

위의 경우는 Yobi가 chunked encoding으로 응답을 하기 위해 HTTP/1.1를 요구하는데, nginx가 HTTP/1.0으로 요청을 보낸 것으로 보입니다. nginx가 HTTP/1.1로 요청을 보내도록 proxy 설정을 고치거나 하셔야 할 것 같습니다.

**Comment by welikeheon** [comment]
빠른 답변에 감사드립니다.
proxy에서 1.1로 보내도록 했는데요.
코드를 보러 가거나 git을 push하면 서버와 페이지가 열리지 않고, 서버가 잠시동안 먹통이 되는 문제가 생기네요.. putty도 갑자기  inactive 됩니다..;; 

서버 문제인가요?;;

**Comment by npcode** [comment]
코드에 접근하거나 git push를 하면 JGit이 Git 저장소에 접근하면서 디스크를 많이 읽고쓰게되는데 그게 원인이 아닌가 싶네요. Disk I/O 사용률을 점검해보시는 것이 어떨까요?

**Comment by welikeheon** [comment]
빠른 답변에 감사드립니다.

덕분에 문제는 잘 해결되었습니다.
포트 9000을 달고 했을때에는 문제가 없었기에 디스크 IO 문제는 아니었습니다.

혹시 NGINX 에서 설정에 문제가 있나 싶어서 다시 한번 살펴봤는데요. 역시 NGINX 문제였던것 같습니다.

후에 누군가에게 도움이 될 것 같아 일단 제 nginx 설정 남깁니다.

![2015-06-18 9 01 13](https://cloud.githubusercontent.com/assets/8732888/8230651/496ba6c8-15fd-11e5-948d-86296662c57c.png)


감사합니다 :)
