### ISSUE TITLE
SVN 사용중 Yobi가 죽었습니다. 로그 내용을 첨부합니다.

### ISSUE THREAD

**Issue by glsseact** [naver/yobi#943]
첨부된 사진과 같습니다.
![default](https://cloud.githubusercontent.com/assets/9211595/8610706/c99248e4-26f0-11e5-82c4-3a455eef5e4d.PNG)

개발 환경에 대해서 필요하다면 어떤 정보를 알려드려야 할까요?
개인 서버이며, Xubuntu 에서 동작하고 있고 0.7.3 버전 입니다. 
혹시.. 0.8.0.에서 해결된 문제 인가요?

**Comment by npcode** [comment]
죽기 직전에 logs/root.log에 남아있는 로그가 저것인지요?

**Comment by glsseact** [comment]
네, 맞습니다.

**Comment by npcode** [comment]
로그에서는 딱히 죽을만한 에러가 남아있지는 않네요. logs에 로그를 남기지도 못하고 죽은 것 같아요.

하지만 그런 경우에도 standard error로는 로그를 남기지 않을까 싶군요. standard error를 로그로 남기도록 하고 다시 시작하신뒤에 추후 재현되면 그 로그를 확인해주시면 문제 해결에 도움이 될 것 같습니다.

저희는 다음과 같은 방법으로 standard error를 logs/stderr 파일에 기록합니다.

    _JAVA_OPTIONS="-Xmx12g -Xms12g" nohup bin/yob 3>&1 1>&2 2>&3 | tee -a $YOBI_HOME/logs/stderr &

**Comment by glsseact** [comment]
답변 감사합니다. 같은 증상이 발생하면 다시 올리겠습니다.
