### ISSUE TITLE
svn 사용시 다음과 같은 오류가 발생할 경유에는 어떻게 대처를 해야 하나요?

### ISSUE THREAD

**Issue by namineya** [naver/yobi#949]
svn을 이용하여 업로드를 시도 하였더니 몇일전까지 잘되던 commit이 안되기 시작하였습니다.
버전은 0.8.2이구요 에러 내용은 아래와 같습니다.

[error] play - Cannot invoke the action, eventually got an error: org.tmatesoft.svn.core.SVNException: svn: E160006: Revision file '/data/activator-1.2.10-minimal/yobi/repo/svn/140922_xxxx/xxxx/db/revs/0/40' does not exist, and r40 is not packed

어떻게 조치를 하면 좋을지 조언 부탁 드립니다.

**Comment by npcode** [comment]
커밋이 손상된 것이 아닌가 하는 생각이 드네요. svnadmin으로 verify해서 확인해보시고 load&dump로 복원하시면 되지 않을까 싶습니다.

참고: http://stackoverflow.com/questions/5543285/how-do-i-fix-a-repository-with-one-broken-revision

**Comment by namineya** [comment]
잘해결 되었습니다.
감사합니다.^^
