### ISSUE TITLE
삭제시킨 사용자 재가입 여부

### ISSUE THREAD

**Issue by jmsuhl** [naver/yobi#952]
관리자가 임의로 삭제시킨 사용자를 회원 재가입을 하고싶은데, 

삭제된 사용자임에도 불구하고, 같은 아이디로 회원가입을 하면 아이디 중복체크에서 걸리네요.

삭제된 계정으로 로그인을 하면 삭제된 회원이라고 메시지가 뜹니다.

해결할 수 있는 방법이 있을까요?

**Comment by npcode** [comment]
사용자 삭제후 다른 사용자가 그 사용자의 login id로 가입하게 되면 예상치 못한 문제가 발생할 것이 우려되어 그렇게 만들어져 있는 상태입니다. (부작용을 감수하고) DB에 직접 들어가서 삭제된 사용자의 login id를 변경한다거나 하는 방법밖에 없을 것 같습니다.

**Comment by jmsuhl** [comment]
Yobi의 embedded DB인 h2 를 사용하는데, 사용자 삭제는 어떻게 해야할까요?
리눅스 서버에 설치되었는데, 데이터를 볼 수 있는 곳을 못찾았습니다.

**Comment by npcode** [comment]
h2 쉘에 들어가서 하실 수 있습니다. 예를 들어 저 같은 경우는 다음과 같이 실행합니다.

```
java -cp ~/.ivy2/cache/com.h2database/h2/jars/h2-1.3.176.jar org.h2.tools.Shell -user "" -password "" -url "jdbc:h2:file:./nforge;CACHE_SIZE=131072;MODE=PostgreSQL;TRACE_LEVEL_FILE=3;LOCK_TIMEOUT=200;MVCC=FALSE;MV_STORE=FALSE;LOCK_MODE=0;AUTO_SERVER=TRUE"
```

웹브라우저로 콘솔을 실행하는 방법도 있고요.

참고: http://www.h2database.com/html/tutorial.html#tutorial_starting_h2_console

**Comment by jmsuhl** [comment]
감사합니다~^^
