### ISSUE TITLE
0.8.1 버전에서 OOM 발생 문제

### ISSUE THREAD

**Issue by oshnew** [naver/yobi#953]
안녕하세요. 먼저 좋은 프로그램 만들어주셔서 감사합니다.

얼마전에 회사에 YOBI를 도입해서 쓰고있는데요. 
너무 빈번하게 OOM발생으로 죽어버리네요.

VM옵션은 아래와 같습니다.
 -server -Xms2048m -Xmx2048m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:NewRatio=3

죽을 때 힙덤프 남겨서 MAT로 분석해보니까 아래처럼 ConcurrentHashMap이 대부분의 메모리를 차지하고 있네요.
One instance of "java.util.concurrent.ConcurrentHashMap" loaded by "<system class loader>" occupies 1,788,303,776 (91.80%) bytes.

혹시, 패치버전이 있거나 튜닝 등의 방법이 있을까요?

![default](https://cloud.githubusercontent.com/assets/3302316/8982471/8f9966ba-36fc-11e5-97b5-72b82bce7e3f.PNG)

**Comment by npcode** [comment]
안타깝게도 메모리 관련 문제는 해결하지 못하고 있습니다. 메모리가 낭비되고 있다는 생각은 하고 있는데 개선할 여력이 안되네요.

저희는 일단 그냥 넉넉하게 4~8GB 할당하고 쓰고 있는 중입니다;

**Comment by oshnew** [comment]
네 그렇군요..
바쁘신데 답변 감사드립니다.~~
