### ISSUE TITLE
요비를 신규 서버로 이관 문의

### ISSUE THREAD

**Issue by gunil** [naver/yobi#954]
요비를 다른 서버로 이관 하려고 하는데요. 

기존 서버(윈도우)에서의 버전은 6점대 버전으로 가이드(#924) 대로 실행하는 중에
신규 서버(윈도우)에서 DB 복원이 제대로 되지 않아서요. 

java -cp ./target/universal/stage/lib/com.h2database.h2-1.3.176.jar org.h2.tools.RunScript -url jdbc:h2:file:yobi -user "" script backup_file_name.zip -options compression zip 

옮기는 서버는 최신버전인 0.8.2로 세팅 중에 있습니다.
java -cp ./lib/com.h2database.h2-1.3.176.jar org.h2.tools.RunScript -url jdbc:h2:file:yobi -user "" script backup_file_name.zip -options compression zip 

복원시 기존 폴더 형태와 다른데 com.h2database.h2-1.3.176.jar 파일 경로만 맞추어 주면 되는 것이 아닌가요.? 

Runs a SQL script against a database.
Usage: java org.h2.tools.RunScript <options>
Options are case sensitive. Supported options are:
[-help] or [-?]     Print the list of options
[-url "<url>"]      The database URL (jdbc:...)
[-user <user>]      The user name (default: sa)
[-password <pwd>]   The password
[-script <file>]    The script file to run (default: backup.sql)
[-driver <class>]   The JDBC driver class to use (not required in most cases)
[-showResults]      Show the statements and the results of queries
[-checkResults]     Check if the query results match the expected results
[-continueOnError]  Continue even if the script contains errors
[-options ...]      RUNSCRIPT options (embedded H2; -*Results not supported)
See also http://h2database.com/javadoc/org/h2/tools/RunScript.html
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Feature not supported:
"script" [50100-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.h2.message.DbException.get(DbException.java:178)
        at org.h2.message.DbException.get(DbException.java:154)
        at org.h2.util.Tool.throwUnsupportedOption(Tool.java:69)
        at org.h2.util.Tool.showUsageAndThrowUnsupportedOption(Tool.java:58)
        at org.h2.tools.RunScript.runTool(RunScript.java:131)
        at org.h2.tools.RunScript.main(RunScript.java:69)

**Comment by doortts** [comment]
script 앞에 - 가 빠져서 옵션이 틀렸다고 나오는것 같은데요. ^^;;

```
java -cp ./lib/com.h2database.h2-1.3.176.jar org.h2.tools.RunScript -url jdbc:h2:file:yobi -user "" -script backup_file_name.zip -options compression zip
```

**Comment by gunil** [comment]
네넵 그대로 복사해서 사용하다 보니..^^;;
확인 감사드립니다.

DB 복원하여 yobi.bat로 실행하였습니다.
프로젝트는 그대로 다 나오는듯 한데요. (회원 로그인도 잘 됩니다)

단 모든 이미지가 노출되지 않고 각 프로젝트의 Readme 내용이 노출되지 않습니다.
혹 설정 파일에서 경로 수정 되어야 하는 부분이 있을까요? 

현재 yobi 설치된 경로는 C:\tool\yobi-0.8.2에 설치 되어 있습니다. 
(git으로 설치하지 않고 파일로 받아서 설치)

**Comment by npcode** [comment]
uploads와 repo 디렉토리를 찾지 못하고 있는 것 같네요. 이 디렉토리들은 어디에 있는지요?

**Comment by gunil** [comment]
네 bin 폴더 아래에 생성해서 프로필 이미지 및 파일첨부 노출되는 것은 확인하였습니다.

허나 게시글 내 이미지들이 보이지가 않습니다.
기존에는 파일 첨부 후 본문에 넣기 시 `/files/2761`
현재 본문에 넣기 하면 `/yobi/files/2761` 형태로 노출됩니다.

물론 도메인 주소도 기존 주소에 yobi가 포함이 되구요. 
경로를 설정부분에서 바꿀 수 있는 문의 드립니다.

또한, 사이트 관리자 계정은 새로 추가된 부분인듯 한데 최신 버전으로 이관시 이 계정을 임의로 추가할 수 방법이 있는지도 궁금합니다.

**Comment by npcode** [comment]
conf/application.conf 파일에 application.context가 "/yobi"로 설정되어있나요? /yobi로 url이 시작한다면 그럴 가능성이 있어보이네요.

사이트 관리자 계정은 새로 추가된 기능이 아닌데요. 아직 사이트 관리자를 추가하는 기능은 없습니다. 오직 "admin" 사용자만이 사이트 관리 권한을 갖습니다.

**Comment by gunil** [comment]
@npcode 
확인해 보았는데요. 말씀 주신 application.context 부분이 존재하지 않습니다. 
참고로 요비 설치 버전은 최신 버전(0.8.2)입니다. 

사이트 관리자 계정이 있기전에 요비를 생성(2013년)했어서 관리자 계정을 이관된 신규 버전에서 어떻게 생성하는지 문의 드렸습니다.

#484 이슈 확인  해보니 답변중 아래 내용을 확인하였습니다.

conf/application.conf에 보면 application.secret 이란 설정값이 있는데, 이 값을 conf/application.conf.default에 있는 application.secret 값으로 대체하신 뒤 요비를 재시작하시면 관리자 계정 설정 페이지가 나타납니다.

최신 버전에서는 application.conf.default이 존재하지 않는데 어떻게 해야할까요?

**Comment by npcode** [comment]
@gunil 비밀번호에 대한 건이라 메일로 회신드렸습니다.

**Comment by gunil** [comment]
해결 되었습니다. 빠른 답변으로 감사드립니다.^^
파일을 제대로 읽어오지 못하는 이슈였습니다.
