### ISSUE TITLE
IIS로 SMTP 세팅시 conf 설정값

### ISSUE THREAD

**Issue by gunil** [naver/yobi#955]
윈도우 환경에서 IIS로 SMTP 세팅할 경우 application.conf 설정을 어떻게 해야 할까요?

### Mailer
smtp.host = smtp.gmail.com
smtp.port = 465
smtp.ssl = true
smtp.user = yourGmailId
smtp.password = pass
smtp.domain = gmail.com
smtp.mock = false
smtp.archive.size = 5

**Comment by sappho192** [comment]
혹시 해결하셨다면 어떻게 하신건지 알려주실 수 있으세요?
