### ISSUE TITLE
두개의 Yobi 시스템 통합 방안 문의

### ISSUE THREAD

**Issue by nestor79** [naver/yobi#958]
현재 두개의 Yobi 를 설치해서 각각 운영했었는데 이를 한개의 시스템으로 통합 하려고 합니다.
수작업을 통해서라도 통합할 수 있는 방안이 있을까요?
DB를 sql 덤프 받아서 검토 해보았는데 수작업으로 하기엔 좀 무리가 있을 것 같고,
프로젝트 단위로 dump/import 를 할 수 있는 방법이 없을까요?

**Comment by npcode** [comment]
1.0 이후에는 API를 이용해서 옮길 수 있을 것 같지만 현 시점에서는 어려울 것 같네요.

**Comment by nestor79** [comment]
네 알겠습니다. 1.0까지는 우선은 두개의 시스템으로 운영해봐야 겠습니다.
감사합니다.
