### ISSUE TITLE
서버사이드 마크다운 렌더링에 관한 의견

### ISSUE THREAD

**Issue by taggon** [naver/yobi#959]
[marked와 관련한 문제를 설명한 글](https://medium.com/yobi-team/yobi-0-8-2%EC%97%90%EC%84%9C-deprecated%EB%90%9C-thread-stop-%EC%9D%84-%EC%93%B0%EB%8A%94-%EC%9D%B4%EC%9C%A0-39f5f56207d6)을 보고 드리는 의견입니다.

문제가 되는 방법이라면 처음부터 완벽한 결과물을 만들지 않는 쪽으로 생각해도 될 것 같습니다.
클라이언트 사이드에서 marked를 통해 이슈 마크업을 dummy element로 렌더링하도록 하고, 페이지를 읽어들인 다음에 검증해서 실제로 존재하는 이슈만 링크로 만드는 방법도 있지 않을까요. 예를 들어, marked에서는 다음과 같은 결과물만 만듭니다.

```
<span class="issue">#1234</span> … <span class="issue">#4567</span>
```

페이지를 읽어들인 다음 `span.issue`를 훑으며 아이디를 수집해서 서버에서 검증하도록 전송하고 서버에서는 실제로 존재하는 것만 반환합니다.

```
{"valid": ["1233", "1238"]}
```

클라이언트 사이드에서 그 결과를 받아서 실제로 존재하는 엘리먼트만 링크로 변환하고 나머지 존재하지 않는 dummy element는 unwrap 하는 겁니다.

```
존재한다면: <a href="…">#1234</a>
존재하지 않는다면: #4567
```

Yobi를 사용해보지 않아서 이 방법이 적절한지는 잘 모르겠지만, 3rd party JS를 작성할 때 종종 사용하던 방식이라 남겨봅니다.

**Comment by npcode** [comment]
좋은 의견 감사드립니다. 사실 이 방식이 최초 제안된 방식이었는데 서버에서 검증과정 거칠거면 그냥 서버에서 렌더링을 다 하면 되지않냐고 해서 지금의 서버렌더링 방식이 만들어진 것이었죠...

1.0에서는 이 방식과 서버 렌더링을 둘 다 이용한 방식으로 가게 되지 않을까 싶습니다. (알림메일 발송시에도 마크다운 렌더링을 해야해서 서버렌더링을 아예 포기하기가 쉽지 않네요)

**Comment by taggon** [comment]
메일이 문제라면 아무래도 서버 렌더링 방식을 고수할 수 밖에 없겠네요.
답변 감사드리며, 이 이슈는 닫겠습니다. :)
