### ISSUE TITLE
http://demo.yobi.io/

### ISSUE THREAD

**Issue by injiyoung** [naver/yobi#961]
데모 접속이 안됩니다~

**Comment by audi0** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
조성찬(sungchan.jo@navercor...) 님은 현재 부재중입니다.</br>
보내신 메일 <[yobi] http://demo.yobi.io/ (#961)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
조성찬(sungchan.jo@navercor...) 님이 남기신 메시지 입니다.
--------------------------------------------
[Absence period : 2015-08-17 00:00 ~ 2015-08-21 23:59 GMT +09:00]<br>8.17~21 기간 동안 리프레시 휴가로 부재 중입니다. 급한 연락은 라인이나 WorksMobile로 주시기 바랍니다.
--------------------------------------------

**Comment by doortts** [comment]
제보 감사합니다. 살렸습니다. : )
