### ISSUE TITLE
activator에서 start를 하면 무수히 많은 에러가 출력됩니다.

### ISSUE THREAD

**Issue by Funalism** [naver/yobi#964]
[error] Syntax error, parameterized types are only available if source level is 5.0
[error] ----------
[error] 3203. ERROR in /home/dev/yobi/app/validation/ExConstraints.java (at line 52)
[error]         public static class RestrictedValidator extends Constraints.Validator<Object> implements ConstraintValidator<Restricted, Object> {
[error]                                                                                                  ^^^^^^^^^^^^^^^^^^^
[error] The type ConstraintValidator is not generic; it cannot be parameterized with arguments <ExConstraints.Restricted, Object>
[error] ----------
[error] 3204. ERROR in /home/dev/yobi/app/validation/ExConstraints.java (at line 52)
[error]         public static class RestrictedValidator extends Constraints.Validator<Object> implements ConstraintValidator<Restricted, Object> {
[error]                                                                                                                      ^^^^^^^^^^^^^^^^^^
[error] Syntax error, parameterized types are only available if source level is 5.0
[error] ----------
[error] 3205. ERROR in /home/dev/yobi/app/validation/ExConstraints.java (at line 70)
[error]         for (String word : words) {
[error]              ^^^^^^^^^^^^^^^^^^^
[error] Syntax error, 'for each' statements are only available if source level is 5.0
[error] ----------
[error] 3206. ERROR in /home/dev/yobi/app/validation/ExConstraints.java (at line 81)
[error]         public Tuple<String, Object[]> getErrorMessageKey() {
[error]                      ^^^^^^^^^^^^^^^^
[error] Syntax error, parameterized types are only available if source level is 5.0
[error] ----------
[error] 3206 problems (3198 errors, 8 warnings)
[error] (compile:compile) javac returned nonzero exit code

----------------------------------------------------------------------------------------------------------------------
안녕하세요. 
nForge에서 Yobi로 넘어오는 중인 유저입니다.
다름이 아니고, 액티베이터에서 start를 하거나, run을 하면 무수히 많은 에러가 뜹니다.
기본 yobi-0.8.2를 구동시킬땐 문제 없이 작동해서 홈페에지에서 관리자 계정까지 만들고
프로젝트까지 생성하는데 큰 문제가 없었지만, 
소스코드를 빌드해서 올려보려고 하니, 이거 원 에러가 너무 많아서 수정할 수가 없네요
무슨 문제일까요?
Yobi를 올린 시스템은 CentOS 6.4 32bit 환경이고, jdk는 1.7.0_71이 설치되어있습니다.
도와주세요~^^

**Comment by npcode** [comment]
자바 컴파일러 설정 문제인 것 같은데요. 이유는 모르겠지만 사용하시는 시스템에서 javac의 compliance level이 1.4 이하로 낮게 설정되어있는 것 같습니다.

**Comment by Funalism** [comment]
@npcode 안그래도 자바 버전문제말곤 큰 이유가 없는듯 하여 최신버전으로 올려서 테스트하니 문제 없이 진행되었습니다. 클로즈하러 왔는데 댓글 달아주셨네요 감사합니다^^
일단은 닫고 추가적으로 궁금한 사항이 있어서 새로운 이슈로 남기도록 하겠습니다!
감사합니다.

**Comment by Funalism** [comment]
혹 저와 비슷한 문제를 겪으신분들은 자바 최신버전으로 올리셔서 해결하시면 될 듯 합니다.
