### ISSUE TITLE
초기설치상태로 회귀하려면 어떻게 해야할까요?

### ISSUE THREAD

**Issue by Funalism** [naver/yobi#966]
안녕하세요. 요 몇일 Yobi 셋팅하느라 시간가는 줄 모르는 1인 입니다.
오늘은 기존에 9000번 포트로 실행되던 Yobi를 
스타트 옵션에 port 80으로 변경하여 실행하였습니다.
그랬더니 관리자계정을 입력하라는 새로운 메시지가 나와서, 기존관리자 정보를 넣었더니
이미 존재하는 메일이라고 생성이 안되네요. 
검색해본 바로는 yobi.h2.db를 지우면 된다고 하셔서, yobi.h2.db가 있는 폴더 /yobi/target/universal/에 stage를 다 날리고, 다시 activator start로 시작을 하였습니다.
다 삭제가 된줄 알고 기존에 관리자정보를 다시 입력했는데 역시나 이미 존재하는 메일이라고 나오네요?
제가 뭘 잘못한 걸까요? 도와주세요~ ㅎ

**Comment by npcode** [comment]
> 검색해본 바로는 yobi.h2.db를 지우면 된다고 하셔서, yobi.h2.db가 있는 폴더 /yobi/target/universal/에 stage를 다 날리고, 다시 activator start로 시작을 하였습니다.
다 삭제가 된줄 알고 기존에 관리자정보를 다시 입력했는데 역시나 이미 존재하는 메일이라고 나오네요?

만약 그렇다면  /yobi/target/universal/ 밑에 있던 yobi.h2.db가 현재 사용중인 db가 아닐 가능성이 큽니다. https://github.com/naver/yobi#옵션 을 보시고 홈 디렉토리를 직접 지정해보시겠어요?

**Comment by Funalism** [comment]
@npcode 답변 감사합니다^^. 근데 이상한 것은 관리자계정정보만 남아있다는 겁니다. 삭제전 vi로 db파일을 열어서 관리자메일, 전에 가입되었던 유저메일이 존재하였으나, stage 폴더 삭제 후 db파일을 열어서 보았더니 관리자메일은 존재하고, 기존 가업된 유저메일은 확인이 되지 않아 의아합니다.
다만, 말씀하신것처럼 옵션을 다시 주고 시작해보겠습니다.
감사합니다^^

**Comment by Funalism** [comment]
@npcode stage 폴더는 그대로 나두고 yobi.h2.db만 삭제 후 다시 하니 되네요. 흠. 뭔가 잠시 꼬여있었나봅니다. 다음부턴 이것저것 해보고 이슈에 질문해야겠네요. 어제도 그렇고 제가 넘 성의없이 질문하는듯 합니다. 다음부턴 신중하게 질문을 해야겠습니다 ㅠㅠ 감사합니다.

**Comment by npcode** [comment]
말씀하신대로 DB 파일 경로가 꼬이는(?) 경우가 종종 있습니다. Play 2.3부터 희한하게도 기본적으로 target 디렉토리 밑에 DB파일을 만들다보니 그렇게 되었습니다. 그러다보니 사용자가 YOBI_HOME 설정으로 직접 지정한 홈 디렉토리에도 DB가 생기고 target 디렉토리 밑에도 DB가 생겨서 혼란을 초래하고는 합니다. 혼란을 줄이기 위해 YOBI_HOME을 항상 설정하는것을 권해드립니다.

**Comment by Funalism** [comment]
@npcode 넵 ^^ 감사합니다
