### ISSUE TITLE
application.conf 수정 후 적용이 안됩니다.

### ISSUE THREAD

**Issue by Funalism** [naver/yobi#967]
안녕하세요. 
application.conf 수정 후 적용이 안되서 질문남깁니다.
동일한 질문이 이미 많이 올라왔고, 답변주신 코멘트로 해봤으나 제대로 적용이 되지 않네요.
제가 해본 방법은 다음과 같습니다.

1. stage/conf/application.conf 를 수정
    -> application.siteName="ABC"
2. yobi/conf/application.conf.default 경로를 -Dconfig 옵션을 주어 실행
    -> start -Dhttp.port=80 -Dconfig.file=/home/dev/activator-1.2.10-       
        minimal/yobi/conf/application.conf.default
    -> 마찬가지로 application.conf.default에서 application.siteName="ABC"로 수정

두가지 방법을 해봤으나 제대로 적용이 되지 않네요. 
그리고 -DapplyEvolutions.default=true 이 옵션은 어떤건가요? 
위 옵션을 추가해서 구동했음에도 동일합니다.
conf/Message.kr-KO 내의 app.name="ABC" 수정했으나, 적용이 안되네요. 혹시몰라 message도 수정했습니다. 
뭐가 문젤까요.?

**Comment by Funalism** [comment]
conf/Message.kr-KO 내의 app.name="ABC" 수정했으나, 적용이 안되네요. 
뭐가 문젤까요. ㅠ?

**Comment by npcode** [comment]
일단 메시지 파일은 수정할 필요가 없고, application.conf만 수정하시는 것이 맞습니다.

1번과 같이 해서 안된다면, stage/conf/application.conf 가 현재 설정 파일이 아닌 것입니다.

2번과 같은 경우는, 조금 이상하기는 하지만(application.conf.default는 직접 사용하기 위한 설정 파일이 아니라 템플릿이므로) 일단 되긴 되어야합니다. 어떤 이유에서인지 -Dconfig.file을 무시하는 것 같네요. 한번 README의 가이드대로 패키지로 실행해보시겠어요?

그리고 `-DapplyEvolutions.default=true` 옵션은 이 문제와 관련이 없을 것입니다.

**Comment by Funalism** [comment]
@npcode 감사합니다. 이제서야 코멘트를 다네요. 
일단 확인 해보고 문제시 다시 질문하도록 하겠습니다. 일단 어떤문제인지 확인하면 이슈를 새롭게 달고 이 이슈는 클로으즈 하겠습니다. 감사합니다!^^
