### ISSUE TITLE
절대주소로 접근 가능한 web page publish 기능 요청드립니다.

### ISSUE THREAD

**Issue by JmyL** [naver/yobi#975]
github.io와 같이 특정 branch로 push한 파일을 절대경로로 접근 가능한 기능이 제공 가능할까요?

새롭게 push한 경우 변경된 SHA1-ID가 포함된 web 주소를 새롭게 배포해야 해서 불편함이 있습니다.

혹시 이미 있는 기능인가요? ^^;

**Comment by npcode** [comment]
/files/<브랜치>/파일명 으로 접근하시면 될 것 같습니다.

예:
 
    http://repo.yobi.io/naver/yobi/files/master/README.md

**Comment by JmyL** [comment]
네 충분합니다^^ 감사합니다!

**Comment by JmyL** [comment]
특정 브랜치를 files/브랜치이름 없이 github.io/파일이름 과 같이 접근하는 기능을 검토 부탁드립니다. 아무래도 이와같이 하는 편이 경로 공유에 좋아 보입니다.

**Comment by npcode** [comment]
웹 서버(아파치 등)의 virtual hosting+redirect 기능을 통해서 해결하는 편이 나을 것 같습니다. proj.owner.yobi.io/README.md가 repo.yobi.io/ower/proj/files/master/README.md로 리다이렉트되는 식으로 설정하면 될 것 같네요.

**Comment by JmyL** [comment]
네 감사합니다.
