### ISSUE TITLE
글 작성 > Markdown > Checkbox 기능 문의

### ISSUE THREAD

**Issue by socketbear** [naver/yobi#980]
안녕하세요~

Markdown 안에 Checkbox 기능이 수행되려나 하고, 아래와 같이 써보니 뭔가 구성되는 것 같더군요.
근데 아래와 같이 태그만 나오고, 기능은 수행되지 않습니다.

자세히 살펴보니, ` " `기호가 처음과 시작 부분에 붙어 있군요.

이 기능 사용할 수 있게 구성해 주시면 감사하겠습니다.

아래는 예시입니다.

----- 아래 -----
1. 작성 문 : ` [ ] test`
2. 결과
![image](https://cloud.githubusercontent.com/assets/3022713/10271964/f933eeca-6b53-11e5-9867-b82780a4d988.png)

**Comment by doortts** [comment]
안녕하세요? 현재 저희가 사용하는 javascript library인 marked에서는 github 스타일의 checkbox 를 지원하지만 이게 말 그대로의 화면 rendering만 지원하고 있습니다. 즉, 이야기 주신대로 서버에서도 해당 기능을 만들어야 가능합니다만 현재 만들어져 있지 않습니다. 
아쉽지만 일정상 해당 기능에 대한 지원은 당분간은 어려울 것 같습니다.. : (

**Comment by socketbear** [comment]
아~ 그렇군요~
답변 주셔서 감사합니다!!
