### ISSUE TITLE
conf를 수정하면 ADMIN을 새로 생성하라고 뜹니다.

### ISSUE THREAD

**Issue by UnRyongPark** [naver/yobi#989]
안녕하세요 :)
사내 프로젝트 관리에 YOBI를 적용하려고 이리저리 설치작업을 진행하고 있습니다.

Activator통해서 실행하는건 [링크](https://github.com/naver/yobi/issues/983#issuecomment-149406397)에 코멘트한 것 같이 진행이 안되서 실패하고,
zip파일 받고(0.8.2버전이더군요) 압축풀고 그냥 bat파일을 실행했더니 conf파일이 인식이 안되서 고생을 하다.

bat파일 실행 전에 JAVA_OPTS 설정하는 것을 발견하여 세팅 후 실행하니 conf를 인식하게 되어 기쁜마음으로 세팅하던 중, 이메일 설정을 위해 conf파일을 수정->저장 하고 다시 실행했더니...
admin을 다시 설정하라고 뜨네요;; 혹시몰라서 다시 기입하고 몇번씩 테스트를 진행했는데 사용자는 살아있고 관리자에 설정한 이메일도 살아있는데 계속 강제로 admin 설정 페이지가 나오네요;;

>현재 세팅은 다음과 같습니다.
> Windows 2012 R2 64bit JDK 1.7.80
> F:\yobi

**Comment by npcode** [comment]
그 페이지가 다시 뜨는 이유는 설정파일의 application.secret이 기본값 그대로인 상태이기 때문입니다. 그럴 수 있는 가능성은:

1. Yobi가 엉뚱한 설정 파일을 읽어들이고 있음
2. 진짜로 설정 파일에서 application.secret이 기본값 그대로

JAVA_OPTS는 어떤 값으로 설정하셨는지요?

**Comment by UnRyongPark** [comment]
> SET JAVA_OPTS=-Dyobi.home=F:/yobi/bin -Dconfig.file=F:/yobi/bin/conf/application.conf -Dlogger.file=F:/yobi/bin/conf/application-logger.xml
2번 문제일 가능성도 있는 것 같습니다
혹시 application.secret값이 실행 후 변경되나요?

**Comment by npcode** [comment]
application.secret 값이 기본값 그대로라면  설치 직후에 처음으로 yobi에 접속한 것으로 간주하고 사이트 관리자 설정 페이지가 뜹니다. 여기서 사이트 관리자를 설정하면 application.secret 값도 같이 변경됩니다.

물론 그냥 직접 설정 파일을 열고 application.sercet 값을 임의의 무작위 값을 넣어주셔도 무방합니다.

만약 값이 다음과 같다면 기본값 그대로인 상태인 것입니다:

    application.secret="VA2v:_I=h9>?FYOH:@ZhW]01P<mWZAKlQ>kk>Bo`mdCiA>pDw64FcBuZdDh<47Ew"

**Comment by UnRyongPark** [comment]
오 감사합니다 :) 
말씀해주신 부분 적용하니 정상작동합니다!!
메일 연동 했어요!!
