### ISSUE TITLE
커밋한 날짜 이상

### ISSUE THREAD

**Issue by jjhangu** [naver/yobi#991]
![image](https://cloud.githubusercontent.com/assets/5935815/10903721/1ca46c3c-8250-11e5-9db6-c58b9343950a.png)

방금 커밋하고 웹페이지에서 확인했는데 커밋한 날짜가 몇초후라고 뜨네요
몇초전을 예상했는데요

**Comment by npcode** [comment]
Git이라면 클라이언트와 서버의 시간이 서로 달라서 그럴 수도 있을 듯 합니다

**Comment by jjhangu** [comment]
Svn 으로 했는데 커밋할때 eclipse svn plugin으로 했습니다.
eclipse  svn 클라이언트와 yobi의 시간차일수도 있겠네요.

**Comment by npcode** [comment]
SVN도 커밋일시를 클라이언트 시간으로 기록하는 모양이군요. 그렇다면 시간차 문제일 것 같습니다.

**Comment by jjhangu** [comment]
넵~!
